### ISSUE TITLE
请问如何单独启动

### ISSUE THREAD

**Issue by 1340691923** [hel-eco/hel-tpl-remote-vue-comp#1]
执行 npm run start 后，弹出的窗口空白一片，控制台打印 We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled.
      Please enable it to continue.

**Comment by fantasticsoul** [comment]
最新版本单独启动还有此问题么

**Comment by wukai900610** [comment]
![image](https://user-images.githubusercontent.com/3339632/202075685-8df530cf-3835-4a32-ba2e-3ae454140faf.png)
这个值不知道为什么是undefined 写成固定值App就可以了

**Comment by vellsuan** [comment]
打包报CP不是内部命令

**Comment by vellsuan** [comment]
![image](https://user-images.githubusercontent.com/25877064/203482671-4eec9b7a-a595-4793-8ab6-e54e9cebac93.png)

**Comment by vellsuan** [comment]
启动一片空白写死输出那个模块也没用

**Comment by vellsuan** [comment]
"hel-dev-utils": "^2.3.4", 这个版本不存在

**Comment by fantasticsoul** [comment]
> 打包报CP不是内部命令

明白了，你是windows系统对么

**Comment by fantasticsoul** [comment]
已引入 sdx 解决 cp 不存在的问题
